version: "3"
services:
  postgres:
    container_name: typeorm_sti_postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
    ports:
      - "54320:5432"
    restart: unless-stopped

volumes:
  postgres:
